// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnu9jHtJJCkiBcDvkC-dh4ail7Gb7GWe8',
    appId: '1:83315809994:web:924ce9835c799809511e33',
    messagingSenderId: '83315809994',
    projectId: 'device-streaming-d34c6191',
    authDomain: 'device-streaming-d34c6191.firebaseapp.com',
    storageBucket: 'device-streaming-d34c6191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApUkhZAnysYM9iU6eaEu3cmH0HdxcfSE',
    appId: '1:83315809994:android:7c236c6b4d63c4de511e33',
    messagingSenderId: '83315809994',
    projectId: 'device-streaming-d34c6191',
    storageBucket: 'device-streaming-d34c6191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEMuKDiOni0ynMSSbjY5waRTxliBi9JLc',
    appId: '1:83315809994:ios:2954cce25055c6ed511e33',
    messagingSenderId: '83315809994',
    projectId: 'device-streaming-d34c6191',
    storageBucket: 'device-streaming-d34c6191.firebasestorage.app',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEMuKDiOni0ynMSSbjY5waRTxliBi9JLc',
    appId: '1:83315809994:ios:2954cce25055c6ed511e33',
    messagingSenderId: '83315809994',
    projectId: 'device-streaming-d34c6191',
    storageBucket: 'device-streaming-d34c6191.firebasestorage.app',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnu9jHtJJCkiBcDvkC-dh4ail7Gb7GWe8',
    appId: '1:83315809994:web:fd24ce8caec08e6c511e33',
    messagingSenderId: '83315809994',
    projectId: 'device-streaming-d34c6191',
    authDomain: 'device-streaming-d34c6191.firebaseapp.com',
    storageBucket: 'device-streaming-d34c6191.firebasestorage.app',
  );

}